# Generated by Django 4.0.6 on 2022-07-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ListNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_to_do_list.note')),
            ],
            bases=('app_to_do_list.note',),
        ),
        migrations.CreateModel(
            name='SimpleNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_to_do_list.note')),
                ('text_note', models.CharField(blank=True, default=None, max_length=500)),
            ],
            bases=('app_to_do_list.note',),
        ),
        migrations.CreateModel(
            name='UrlNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_to_do_list.note')),
                ('url_note', models.URLField(blank=True, default=None, max_length=500, null=True)),
            ],
            bases=('app_to_do_list.note',),
        ),
        migrations.CreateModel(
            name='ListNoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('text', models.CharField(blank=True, default=None, max_length=100)),
                ('list_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_to_do_list.listnote')),
            ],
        ),
    ]
